


// PREPARATION
// INITIALISATION 


// CHAQUE JOUEUR RECOIT UN OBJECTIF

// CHAQUE JOUEUR RECOIT 35 ARMEES

// CHAQUE JOUEUR RECOIT 14 CARTES

// UNE ARMEE EST PLACEE AUTOMATIQUEMENT SUR LES 14 TERRITOIRES DE CHAQUE JOUEUR

// CHAQUE JOUEUR REPARTIT SES ARMEES SUR SES TERRITOIRES



// JEU
// RENFORTS

// CHAQUE JOUEUR RECOIT TERRITOIRES/3 ARMEES +
// CONTINENT SI OCCUPE : 
// OCE : 2, AmeS : 2, AFR : 2, EU : 5, AmeN : 5, ASIE : 7

// CHAQUE JOUEUR PLACE SES NOUVELLES ARMEES


// COMBATS

// CHAQUE JOUEUR PEUT CHOISIR D'ATTAQUER AUTANT DE FOIS QU'IL LE SOUHAITE, SI
	// LES TERRITOIRES SONT FRONTALIERS
	// SI IL GARDE 1 ARMEE SUR CHAQUE TERRITOIRE
	
// L'ASSAILLANT CHOISIT COMBIEN DE TROUPES ATTAQUENT

// L'ASSAILLANT DISPOSE D'UN DE PAR ARMEE ENGAGEE, MAX DE 3

// LE DEFENSEUR DISPOSE D'UN DE PAR ARMEE DEFENDANT, MAX DE 2

// SI LE DEFENSEUR N'A PLUS DE TROUPES, L'ASSAILLANT REMPORTE LE TERRITOIRE
// ET L'OCCUPE AVEC LES TROUPES ENGAGEES

// IL PEUT CHOISIR DE TRANSFERER SES ARMEES DU TERRITOIRE DE DEPART (CONDITION : GARDER 1 ARMEE)

// L'ASSAILLANT PEUT ATTAQUER DE NOUVEAU A PARTIR DU NOUVEAU TERRITOIRE CONQUIS.



// DEPLACEMENTS

// CHAQUE JOUEUR PEUT DEPLACER SES ARMEES, UNE FOIS PAR ARMEE. LES ARMEES SE DEPLACENT D'UN TERRITOIRE SEULEMENT.


